name: ml_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.2.0
  - mlflow>=2.8.0
  - jupyter>=1.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - python-dotenv>=1.0.0
  - pip:
    - -r requirements.txt